version: "3.9"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
      
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db   # mount named volume here

volumes:
  mongo_data:                 # define named volume
